// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsdvykgydhbbjovukgpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzZHZ5a2d5ZGhiYmpvdnVrZ3B6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MzQwOTksImV4cCI6MjA3NDExMDA5OX0.jY4nQ9FzjW0QBY1ocL0p26YKLOfFoqdRWy5GWmq3ww8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});